### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by arnikz** [NLeSC/fairdatapoint#33]
See the code https://github.com/NLeSC/ODEX-FAIRDataPoint/blob/5d7007ae7d22a0cf85aa95cc686028794cf79345/Dockerfile#L22

Build the image and push to [`nlesc-fairdatapoint`](https://hub.docker.com/r/nlesc/odex-fairdatapoint).

**Comment by CunliangGeng** [comment]
Dockerfile is updated and docker compose is added in v0.7.0.
