### ISSUE TITLE
swagger ui

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/fairdatapoint#57]
The [Swagger UI](https://swagger.io/tools/swagger-ui/) is enabled, but not installed and not documented. 

When starting fdp I got following warning:
```
The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>
```

After I ran `pip install connexion[swagger-ui]`. I could access http://localhost/ui/, so I could test out the api using web forms.

Could `connexion[swagger-ui]` be added to the dependencies and can it documented why/how the Swagger UI can be accessed?

**Comment by CunliangGeng** [comment]
Thanks Stefan!

The `swagger-ui` dependency problem has been solved in PR #56 . And the a new PR #58 is updating the README to give the correct Swagger UI link.
