### ISSUE TITLE
Deploy without Docker command incorrect

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/fairdatapoint#61]
I tried to run the `fdp example.com 80 --db='http://dbpedia.org/sparql'` command described at https://github.com/NLeSC/fairdatapoint#deploy-without-docker, but got a error about the graphviz executable `fdp`. 

What did work was
```shell
fdp-run localhost 8888 --db='http://dbpedia.org/sparql'
```

Can the README be updated?

**Comment by sverhoeven** [comment]
Trying out http://localhost:8888/catalog and http://localhost:8888/fdp gave no content and not found errors respectively. 

Can I not use http://dbpedia.org/sparql as a database?

**Comment by CunliangGeng** [comment]
It is a bad example to use 'http://dbpedia.org/sparql', because you cannot use it.
The SPARQL must be a SPARQL database to which you have write access.

**Comment by CunliangGeng** [comment]
solved in #62 .
